// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AccountsService connects store accounts for owned games.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * EpicSignIn finishes the Epic sign-in with the code the page showed
 * (the code alone, or the whole text) and fetches the account's games.
 */
export function EpicSignIn(pasted: string): $CancellablePromise<$models.Accounts> {
    return $Call.ByID(3524560095, pasted);
}

/**
 * EpicSignOut forgets the Epic sign-in and its owned games.
 */
export function EpicSignOut(): $CancellablePromise<$models.Accounts> {
    return $Call.ByID(3912114916);
}

/**
 * Get reports the accounts.
 */
export function Get(): $CancellablePromise<$models.Accounts> {
    return $Call.ByID(1290658952);
}

/**
 * OpenEpicSignIn opens Epic's sign-in page in the browser.
 */
export function OpenEpicSignIn(): $CancellablePromise<void> {
    return $Call.ByID(1099049503);
}

/**
 * OpenSteamKeyPage opens Steam's page for creating a Web API key.
 */
export function OpenSteamKeyPage(): $CancellablePromise<void> {
    return $Call.ByID(2461848680);
}

/**
 * SetGOG turns reading GOG Galaxy's library on or off.
 */
export function SetGOG(on: boolean): $CancellablePromise<$models.Accounts> {
    return $Call.ByID(1922250511, on);
}

/**
 * SetSteamKey stores the user's Steam Web API key (encrypted for this
 * Windows user) and fetches the account's games; "" disconnects Steam.
 */
export function SetSteamKey(key: string): $CancellablePromise<$models.Accounts> {
    return $Call.ByID(3899079451, key);
}

/**
 * Sync fetches the owned games again, in the background.
 */
export function Sync(): $CancellablePromise<void> {
    return $Call.ByID(1509495647);
}
