// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LaunchService starts games and follows them while they run.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as launch$0 from "../launch/models.js";

/**
 * Answer answers a question a hook asked.
 */
export function Answer(questionID: number, option: string): $CancellablePromise<void> {
    return $Call.ByID(411793517, questionID, option);
}

/**
 * Cancel stops a launch that hasn't reached the game yet.
 */
export function Cancel(): $CancellablePromise<void> {
    return $Call.ByID(904310269);
}

/**
 * CloseOverlay hides the in-game overlay.
 */
export function CloseOverlay(): $CancellablePromise<void> {
    return $Call.ByID(4252499543);
}

/**
 * OpenMain opens the main window (from the overlay), leaving the game running.
 */
export function OpenMain(): $CancellablePromise<void> {
    return $Call.ByID(4029110470);
}

/**
 * Play starts a game: hooks first, then the game, then it is followed
 * until it exits.
 */
export function Play(id: number): $CancellablePromise<void> {
    return $Call.ByID(3382391377, id);
}

/**
 * PlayFromArgs starts the game named by "--play <id>", if any. The
 * interface isn't opened for it; the game comes first.
 */
export function PlayFromArgs(args: string[] | null): $CancellablePromise<boolean> {
    return $Call.ByID(3994636312, args);
}

/**
 * QuitGame ends the running game's processes right away.
 */
export function QuitGame(): $CancellablePromise<void> {
    return $Call.ByID(494157406);
}

/**
 * Route tells how a game would start now: direct, store or steamInput.
 */
export function Route(id: number): $CancellablePromise<string> {
    return $Call.ByID(150479176, id);
}

/**
 * Session returns the current (or last) game session.
 */
export function Session(): $CancellablePromise<launch$0.Session> {
    return $Call.ByID(3550337637);
}

/**
 * SetUIMode tells the core which mode the interface shows.
 */
export function SetUIMode(mode: string): $CancellablePromise<void> {
    return $Call.ByID(3330897984, mode);
}

/**
 * Skip skips a hook step that is running.
 */
export function Skip(stepID: string): $CancellablePromise<void> {
    return $Call.ByID(3747112656, stepID);
}
