// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService is the game library, as the frontend sees it.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as meta$0 from "../meta/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseExe lets the user pick the executable that starts the game.
 */
export function ChooseExe(id: number): $CancellablePromise<library$0.Game> {
    return $Call.ByID(794819148, id);
}

/**
 * ConfirmMatch accepts the game's identity, so it leaves Found on this PC.
 */
export function ConfirmMatch(id: number): $CancellablePromise<library$0.Game> {
    return $Call.ByID(3836606500, id);
}

/**
 * Game returns one game.
 */
export function Game(id: number): $CancellablePromise<library$0.Game> {
    return $Call.ByID(976483851, id);
}

/**
 * Games returns every game in the library.
 */
export function Games(): $CancellablePromise<library$0.Game[] | null> {
    return $Call.ByID(399310568);
}

/**
 * Install asks the game's store to install it (owned, not installed).
 */
export function Install(id: number): $CancellablePromise<void> {
    return $Call.ByID(2311012180, id);
}

/**
 * MetaState reports metadata fetching progress.
 */
export function MetaState(): $CancellablePromise<$models.MetaState> {
    return $Call.ByID(2108934609);
}

/**
 * OpenFolder shows the game's folder in Explorer.
 */
export function OpenFolder(id: number): $CancellablePromise<void> {
    return $Call.ByID(211439525, id);
}

/**
 * RefreshMetadata fetches a game's metadata and art again.
 */
export function RefreshMetadata(id: number): $CancellablePromise<void> {
    return $Call.ByID(2213972277, id);
}

/**
 * Rename sets the title shown for a game ("" restores the found one).
 */
export function Rename(id: number, title: string): $CancellablePromise<library$0.Game> {
    return $Call.ByID(760188831, id, title);
}

/**
 * Rescan looks for games again now.
 */
export function Rescan(): $CancellablePromise<void> {
    return $Call.ByID(3402996597);
}

/**
 * ScanState reports what the scanner is doing.
 */
export function ScanState(): $CancellablePromise<$models.ScanState> {
    return $Call.ByID(2418544241);
}

/**
 * SearchSteam looks up titles on the Steam store, to pick the right game.
 */
export function SearchSteam(query: string): $CancellablePromise<meta$0.StoreHit[] | null> {
    return $Call.ByID(582756011, query);
}

/**
 * SetFavorite marks or unmarks a favorite.
 */
export function SetFavorite(id: number, on: boolean): $CancellablePromise<library$0.Game> {
    return $Call.ByID(2150311527, id, on);
}

/**
 * SetHidden hides a game from the library views (or shows it again).
 */
export function SetHidden(id: number, on: boolean): $CancellablePromise<library$0.Game> {
    return $Call.ByID(3616234503, id, on);
}

/**
 * SetMatch says which game this is: a Steam app and its name. The choice
 * is kept across scans, and metadata is fetched for it.
 */
export function SetMatch(id: number, steamAppID: number, name: string): $CancellablePromise<library$0.Game> {
    return $Call.ByID(3788970144, id, steamAppID, name);
}

/**
 * SetPadMode picks how a controller reaches the game: "" (auto), "native" or "steam".
 */
export function SetPadMode(id: number, mode: string): $CancellablePromise<library$0.Game> {
    return $Call.ByID(2840651259, id, mode);
}
