// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncer$0 from "../syncer/models.js";

/**
 * AppInfo describes this build.
 */
export interface AppInfo {
    "version": string;
    "dataDir": string;
    "logFile": string;
}

/**
 * MetaState is what the metadata worker is doing.
 */
export interface MetaState {
    "running": boolean;
    "done": number;
    "total": number;
}

/**
 * PadAction is one controller action.
 */
export interface PadAction {
    "action": string;
    "repeat": boolean;
}

/**
 * Saves is what Syncer knows about a game's saves, for the interface.
 */
export interface Saves {
    /**
     * Syncer is installed
     */
    "installed": boolean;

    /**
     * too old for the launcher API
     */
    "outdated": boolean;

    /**
     * Syncer answered
     */
    "available": boolean;
    "error"?: string;

    /**
     * Syncer has save folders for this game
     */
    "known": boolean;
    "folders": syncer$0.Folder[] | null;
}

/**
 * ScanState tells the frontend what the scanner is doing.
 */
export interface ScanState {
    "running": boolean;

    /**
     * unix seconds
     */
    "lastScan": number;
    "tookMs": number;
    "games": number;
    "added": number;

    /**
     * titles in the game database; 0 until it's downloaded
     */
    "known": number;
    "error"?: string;
}
