// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as syncer$0 from "../syncer/models.js";

/**
 * Accounts are the store accounts owned games come from.
 */
export interface Accounts {
    "steam": StoreAccount;
    "gog": StoreAccount;
    "epic": StoreAccount;
}

/**
 * AddonAction is something an add-on can do for a game.
 */
export interface AddonAction {
    "id": string;
    "label": string;
    "description"?: string;
    "confirm"?: string;
}

/**
 * AddonGame is what one add-on says about a game.
 */
export interface AddonGame {
    "addon": string;
    "name": string;
    "badges": Badge[] | null;
    "lines": Line[] | null;
    "actions": AddonAction[] | null;
    "error"?: string;
}

/**
 * AddonProgress is one progress line of an add-on action.
 */
export interface AddonProgress {
    "addon": string;
    "text": string;
}

/**
 * AddonView is an add-on as Settings shows it.
 */
export interface AddonView {
    "id": string;
    "name": string;
    "version": string;
    "publisher": string;
    "description": string;
    "homepage": string;
    "exe": string;
    "hooks": string[] | null;
    "permissions": Permission[] | null;
    "signed": boolean;
    "sha256": string;
    "enabled": boolean;
    "running": boolean;

    /**
     * State: "off", "on", "changed" (the program changed since approval),
     * "missing" (the program is gone) or "broken" (the manifest is wrong).
     */
    "state": string;
    "error"?: string;
}

/**
 * AppInfo describes this build.
 */
export interface AppInfo {
    "version": string;
    "dataDir": string;
    "logFile": string;
}

/**
 * Badge is a short fact an add-on shows on a game.
 */
export interface Badge {
    "text": string;
    "tone"?: string;
    "tooltip"?: string;
}

/**
 * Line is a labelled value an add-on shows on a game.
 */
export interface Line {
    "label": string;
    "value": string;
}

/**
 * MetaState is what the metadata worker is doing.
 */
export interface MetaState {
    "running": boolean;
    "done": number;
    "total": number;
}

/**
 * PadAction is one controller action.
 */
export interface PadAction {
    "action": string;
    "repeat": boolean;
}

/**
 * Permission is one declared permission, explained.
 */
export interface Permission {
    "id": string;
    "label": string;
}

/**
 * Saves is what Syncer knows about a game's saves, for the interface.
 */
export interface Saves {
    /**
     * Syncer is installed
     */
    "installed": boolean;

    /**
     * too old for the launcher API
     */
    "outdated": boolean;

    /**
     * Syncer answered
     */
    "available": boolean;
    "error"?: string;

    /**
     * Syncer has save folders for this game
     */
    "known": boolean;
    "folders": syncer$0.Folder[] | null;
}

/**
 * ScanState tells the frontend what the scanner is doing.
 */
export interface ScanState {
    "running": boolean;

    /**
     * unix seconds
     */
    "lastScan": number;
    "tookMs": number;
    "games": number;
    "added": number;

    /**
     * titles in the game database; 0 until it's downloaded
     */
    "known": number;
    "error"?: string;
}

/**
 * StoreAccount is one store account as Settings shows it.
 */
export interface StoreAccount {
    "connected": boolean;

    /**
     * the store is on this PC (GOG: Galaxy's library)
     */
    "available": boolean;
    "name"?: string;
    "games": number;

    /**
     * unix seconds
     */
    "synced"?: number;
    "syncing": boolean;
    "error"?: string;
}
