// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppInfo describes this build.
 */
export interface AppInfo {
    "version": string;
    "dataDir": string;
    "logFile": string;
}

/**
 * ScanState tells the frontend what the scanner is doing.
 */
export interface ScanState {
    "running": boolean;

    /**
     * unix seconds
     */
    "lastScan": number;
    "tookMs": number;
    "games": number;
    "added": number;

    /**
     * titles in the game database; 0 until it's downloaded
     */
    "known": number;
    "error"?: string;
}
