// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PadService is the controller: actions, glyph family, rumble and lightbar.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pad$0 from "../pad/models.js";

/**
 * Rumble plays a short effect ("tick", "bump", "confirm", "error",
 * "launch") when the user has haptics on.
 */
export function Rumble(effect: string): $CancellablePromise<void> {
    return $Call.ByID(639488354, effect);
}

/**
 * SetLight tints the DualSense lightbar (#rrggbb) when the user has that on.
 */
export function SetLight(hex: string): $CancellablePromise<void> {
    return $Call.ByID(2435323691, hex);
}

/**
 * State returns the controller in use.
 */
export function State(): $CancellablePromise<pad$0.State> {
    return $Call.ByID(3372721012);
}
