// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SavesService is the game's saves, through Syncer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSyncer opens Syncer's download page.
 */
export function GetSyncer(): $CancellablePromise<void> {
    return $Call.ByID(1796367496);
}

/**
 * OpenSyncer shows Syncer's window.
 */
export function OpenSyncer(): $CancellablePromise<void> {
    return $Call.ByID(2328167404);
}

/**
 * Saves returns what Syncer knows about a game's saves. Syncer is started
 * in the background (without its window) when needed. Answers are kept
 * for a little while; fresh asks again right away.
 */
export function Saves(id: number, fresh: boolean): $CancellablePromise<$models.Saves> {
    return $Call.ByID(959841094, id, fresh);
}
