// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is the user's preferences.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as platform$0 from "../platform/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as settings$0 from "../settings/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFolder asks for a folder whose subfolders are games and adds it.
 */
export function AddFolder(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(2274181668);
}

/**
 * AutoFolders lists the common game folders found on this PC.
 */
export function AutoFolders(): $CancellablePromise<string[] | null> {
    return $Call.ByID(1531654123);
}

/**
 * CopyDiagnostics puts a report for a bug report on the clipboard: versions,
 * settings, what the library holds, controller, Syncer, add-ons, updates,
 * the last crash and the end of the log. It holds no keys or tokens, and
 * the user folder is shortened to %USERPROFILE%.
 */
export function CopyDiagnostics(): $CancellablePromise<void> {
    return $Call.ByID(2190312692);
}

/**
 * Get returns the settings.
 */
export function Get(): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(758947099);
}

/**
 * HasSteamGridDBKey reports whether a SteamGridDB key is stored.
 */
export function HasSteamGridDBKey(): $CancellablePromise<boolean> {
    return $Call.ByID(2555718238);
}

/**
 * Info returns the version and where data is kept.
 */
export function Info(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1352809409);
}

/**
 * OpenLog shows the log file's folder.
 */
export function OpenLog(): $CancellablePromise<void> {
    return $Call.ByID(703170417);
}

/**
 * RemoveFolder stops looking in a watched folder.
 */
export function RemoveFolder(path: string): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1110927849, path);
}

/**
 * ReportProblem opens a new GitHub issue for WaterLauncher.
 */
export function ReportProblem(): $CancellablePromise<void> {
    return $Call.ByID(124522558);
}

/**
 * ReportUIError logs an error the interface ran into (an exception or a
 * rejected promise), so it shows up in the log and in diagnostics.
 */
export function ReportUIError(message: string): $CancellablePromise<void> {
    return $Call.ByID(2064165481, message);
}

/**
 * Save stores new settings; library settings trigger a scan.
 */
export function Save(v: settings$0.Settings): $CancellablePromise<settings$0.Settings> {
    return $Call.ByID(1096834604, v);
}

/**
 * SetStartWithWindows turns starting with Windows on or off.
 */
export function SetStartWithWindows(on: boolean): $CancellablePromise<platform$0.Startup> {
    return $Call.ByID(1866676958, on);
}

/**
 * SetSteamGridDBKey stores (or with "", removes) the SteamGridDB API key,
 * encrypted for this Windows user, and fetches art the stores lacked.
 */
export function SetSteamGridDBKey(key: string): $CancellablePromise<void> {
    return $Call.ByID(1960903710, key);
}

/**
 * StartWithWindows reports whether WaterLauncher starts (in the tray) when
 * you sign in to Windows.
 */
export function StartWithWindows(): $CancellablePromise<platform$0.Startup> {
    return $Call.ByID(1638874264);
}
