// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService lets the interface see and drive updates.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Check looks for a new version now (and downloads it).
 */
export function Check(): $CancellablePromise<void> {
    return $Call.ByID(3964175519);
}

/**
 * Install installs the downloaded update and restarts WaterLauncher.
 */
export function Install(): $CancellablePromise<void> {
    return $Call.ByID(2421731896);
}

/**
 * OpenReleasePage opens the newest release on GitHub.
 */
export function OpenReleasePage(): $CancellablePromise<void> {
    return $Call.ByID(1315509785);
}

/**
 * State reports what the updater knows.
 */
export function State(): $CancellablePromise<$models.UpdateState> {
    return $Call.ByID(2614641198);
}
