// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Settings are the user's preferences. New fields get their default when
 * an older settings file doesn't have them.
 */
export interface Settings {
    /**
     * Library
     * extra folders whose subfolders are games
     */
    "folders": string[] | null;

    /**
     * also look in common game folders on every drive
     */
    "autoFolders": boolean;

    /**
     * recognise Steam emulators, cracks and repacks
     */
    "detectUnofficial": boolean;

    /**
     * keep low-confidence matches in Found on this PC
     */
    "reviewUncertain": boolean;

    /**
     * list games that aren't installed (anymore)
     */
    "showNotInstalled": boolean;

    /**
     * Appearance
     * system, dark, light (desktop mode)
     */
    "theme": string;

    /**
     * deck, console, orbit
     */
    "bigPictureLayout": string;

    /**
     * Big picture and controller
     */
    "openBigPictureOnController": boolean;
    "startInBigPicture": boolean;
    "sounds": boolean;
    "haptics": boolean;
    "lightbar": boolean;
    "psButton": boolean;

    /**
     * auto, playstation, xbox
     */
    "glyphs": string;

    /**
     * While playing
     * close the interface while a game runs (frees its memory)
     */
    "closeWhilePlaying": boolean;

    /**
     * listen (PS button opens the overlay), off (release the controller)
     */
    "padWhilePlaying": string;

    /**
     * Saves, through Syncer
     * sync a game's saves before it starts
     */
    "syncSavesBefore": boolean;

    /**
     * back its saves up after it exits
     */
    "backupSavesAfter": boolean;
}
