// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Kind is a controller family, for the button glyphs.
 */
export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PlayStation = "playstation",
    Xbox = "xbox",
    Nintendo = "nintendo",
    Other = "other",
};

/**
 * State describes the controller in use.
 */
export interface State {
    "connected": boolean;
    "name": string;
    "kind": Kind;
    "dualSense": boolean;

    /**
     * percent, -1 unknown
     */
    "battery": number;
    "wireless": boolean;
    "error"?: string;
}
