// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Folder is one save folder Syncer looks after.
 */
export interface Folder {
    "id": string;
    "label": string;
    "path": string;
    "sync": boolean;
    "backup": boolean;
    "state": string;
    "needBytes": number;
    "errors": number;
    "conflicts": number;
    "exists": boolean;
    "modified": string;
    "backedUp": string;
    "newerOn": string;
    "newerAt": string;
}
