// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StoreHit is one result of a Steam store search.
 */
export interface StoreHit {
    "appId": number;
    "name": string;

    /**
     * small capsule on Steam's CDN (not fetched by WaterLauncher)
     */
    "image": string;
}
