// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Startup is whether WaterLauncher starts when you sign in to Windows.
 */
export interface Startup {
    "on": boolean;

    /**
     * Off in Task Manager's Startup apps: Windows skips it even though
     * it's registered.
     */
    "disabledByUser": boolean;
}
