// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Option is one answer to a question.
 */
export interface Option {
    "id": string;
    "label": string;
}

/**
 * Phase is where a session is.
 */
export enum Phase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * hooks before launch
     */
    Preparing = "preparing",

    /**
     * started; waiting to see the game run
     */
    Starting = "starting",
    Running = "running",

    /**
     * hooks after exit
     */
    Finishing = "finishing",
    Ended = "ended",
    Failed = "failed",
    Cancelled = "cancelled",
};

/**
 * Question is a step asking the user to decide something.
 */
export interface Question {
    "id": number;
    "text": string;
    "options": Option[] | null;
}

/**
 * Session is the game being launched or played.
 */
export interface Session {
    "id": number;
    "gameId": number;
    "title": string;
    "phase": Phase;

    /**
     * how it starts: "direct", "store", "steamInput"
     */
    "route": string;
    "before": StepState[] | null;
    "after": StepState[] | null;
    "question"?: Question | null;

    /**
     * unix seconds; when the game was seen running
     */
    "startedAt"?: number;

    /**
     * played this session
     */
    "seconds": number;
    "error"?: string;
    "note"?: string;
}

/**
 * StepState is a hook step as the interface shows it.
 */
export interface StepState {
    "id": string;
    "label": string;
    "status": string;
    "detail"?: string;
}
